
CREATE TABLE IF NOT  EXISTS WORKSPACE_GATEWAY(
    GATEWAY_ID VARCHAR (255),
    GATEWAY_NAME VARCHAR (255),
    GATEWAY_DOMAIN VARCHAR (255),
    EMAIL_ADDRESS VARCHAR (255),
    GATEWAY_APPROVAL_STATUS VARCHAR (255),
    GATEWAY_ACRONYM VARCHAR (255),
    GATEWAY_URL VARCHAR (255),
    GATEWAY_PUBLIC_ABSTRACT TEXT,
    REVIEW_PROPOSAL_DESCRIPTION TEXT,
    GATEWAY_ADMIN_FIRST_NAME VARCHAR(255),
    GATEWAY_ADMIN_LAST_NAME VARCHAR(255),
    GATEWAY_ADMIN_EMAIL VARCHAR(255),
    IDENTITY_SERVER_USERNAME VARCHAR(255),
    IDENTITY_SERVER_PASSWORD_TOKEN VARCHAR(255),
    DECLINED_REASON VARCHAR(255),
    OAUTH_CLIENT_ID VARCHAR(255),
    OAUTH_CLIENT_SECRET VARCHAR(255),
    REQUEST_CREATION_TIME BIGINT,
    REQUESTER_USERNAME VARCHAR(255),
    PRIMARY KEY (GATEWAY_ID)
);

CREATE TABLE IF NOT EXISTS WORKSPACE_NOTIFICATION (
    NOTIFICATION_ID VARCHAR (255),
    GATEWAY_ID VARCHAR (255),
    TITLE VARCHAR (255),
    NOTIFICATION_MESSAGE TEXT,
    CREATION_TIME BIGINT,
    PUBLISHED_TIME BIGINT,
    EXPIRATION_TIME BIGINT,
    PRIORITY VARCHAR (255),
    PRIMARY KEY (NOTIFICATION_ID),
    FOREIGN KEY (GATEWAY_ID) REFERENCES WORKSPACE_GATEWAY(GATEWAY_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS WORKSPACE_PROJECT(
    PROJECT_ID VARCHAR (255),
    OWNER VARCHAR (255),
    GATEWAY_ID VARCHAR (255),
    PROJECT_NAME VARCHAR (255),
    DESCRIPTION VARCHAR (255),
    CREATION_TIME BIGINT,
    PRIMARY KEY (PROJECT_ID),
    FOREIGN KEY(OWNER) REFERENCES WORKSPACE_USER_PROFILE(AIRAVATA_INTERNAL_USER_ID),
    FOREIGN KEY(GATEWAY_ID) REFERENCES WORKSPACE_GATEWAY(GATEWAY_ID) ON DELETE CASCADE
);